### ISSUE TITLE
新增的挂件无法使用

### ISSUE THREAD

**Issue by TCOTC** [Achuan-2/day-counter#13]
![image](https://github.com/user-attachments/assets/8f186b82-03f3-43bd-a003-b4139434b4a7)

**Comment by Achuan-2** [comment]
应该修复了

**Comment by TCOTC** [comment]
@Achuan-2 打包已经卡住 2 小时了，你可能需要重新运行工作流：https://github.com/Achuan-2/siyuan-widget-dayCounter/actions/runs/10175811810

**Comment by Achuan-2** [comment]
还是打包成功了，暂时不管了哈哈哈
